site_name: Confir
site_url: https://configr.wiektec.com/
repo_url: https://github.com/cwieken/confir
repo_name: cwieken/confir
site_description: A flexible, type-safe configuration management library for Python

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide:
    - Overview: user-guide/index.md
    - Basic Usage: user-guide/basic-usage.md
    - Configuration Classes: user-guide/config-classes.md
    - Custom Loaders: user-guide/custom-loaders.md
  - API Reference:
    - ConfigBase: api/config-base.md
    - config_class: api/config-class.md
    - Loaders: api/loaders.md
    - Exceptions: api/exceptions.md
    - Utilities: api/utils.md
  - Examples: examples.md
  - Contributing: contributing.md